spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 489540681384-omfi6teio1pdkj4skcvrjopak2d10af5.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: Zsw9WJvsyyicAdId1n2C
            client-secret: vn2iuv1jYv
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response